### ISSUE TITLE
Aufklappzeit änderbar?

### ISSUE THREAD

**Issue by Koala** [FriendsOfREDAXO/be_tools#34]
Ist die Zeit, mit der das Seitenmenü aufgeklappt wird, irgendwo änderbar.
Mir geht das einen Augenblick zu schnell, wenn die Maus nur mal eben das Menü streift, zuckt das Menü zum aufklappen schon.

**Comment by Koala** [comment]
### Bisher

Die Aufklappzeit wird über die style.css per transition geregelt.

```css
	nav.rex-nav-main, div.rex-nav-main, 
		.rex-nav-main-title, 
		.rex-nav-main-list>li>a, 
		.rex-nav-main-list>li.rex-has-icon>a>.rex-icon, 
		.rex-nav-main-list .cke5-icon-logo, 
		.rex-nav-main-list .watson-icon-logo 
		{ -webkit-transition: all 0,25s ease; transition: all 0,25s ease; }
```
Leider läßt sich damit das Auf- und Zuklappen nicht sinnvoll zeitlich voneinander trennen. Die Aufklappkurve liefert leider immer ein bescheidenes Ergebnis. Das Aufklappen beginnt immer, egal welche Verzögerung eingestellt wird.

### Versuch

```css
	nav.rex-nav-main, div.rex-nav-main, 
		.rex-nav-main-list>li>a, 
		.rex-nav-main-list>li.rex-has-icon>a>.rex-icon, 
		.rex-nav-main-list .cke5-icon-logo, 
		.rex-nav-main-list .watson-icon-logo 
		{ -webkit-transition: all 0,25s ease; transition: all 0,25s ease; }

	nav.rex-nav-main, div.rex-nav-main, 
		.rex-nav-main-title
		{ 
                transition-delay: 1000ms;
                -webkit-transition: all 0,25s ease; 
                transition: all 0,25s ease; 
                }
```

Einen Teilerfolgt konnte ich mittels `transition-delay` erziehlen. Es ist noch nicht ganz das, was ich mir darunter vorstelle, aber immerhin ein Anfang. 
Das Aufklappen wird lange genüg hinausgezögert, um das Menü nicht beim bloßen überfahren mit der Maus aufspringen zu lassen.
Einen kleinen, aber zu verschmerzlichen Nachteil gibt es. Der Delay-Effekt wirkt sich auch auf das Zusammenklappen des Menüs aus. Also so lange es dauert, bis es aufgeklappt ist, dauert es auch, bis es wieder verschwunden ist. Nach einigem ausprobieren haben sich die 1000ms als ganz akzeptabel herausgestellt.





### Alternative bzw. Erweiterung zum Delay-Effekt

Wie wäre es, zwei Sticky-Butten zu haben? Einen oberhalb der Icons und einen rechts (wie bisher).
Der oberhalb der Icons ist immer sichtbar, wenn aktiviert (angepinnt). Wenn angeklickt, bleibt das Menü geschlossen und die Navigation erfolgt nur über die Icons. Deaktivierung per anklicken ... oder/und es wird (zusätzlich) eine sehr große Zeit bei `transition-delay` verwendet, mit der das Menü trotz des angepinnten immer noch sichtbar gemacht werden kann. Sozusagen als Fall-Back.
Wenn nicht aktiviert (nicht angepinnt), erscheint der Über-den-Icons-Pin nur, wenn das Menü voll aufgeklappt ist.

Hilfreich wäre, wenn die Icons ihren Namen noch anzeigen würden, was sie bei mir nicht tun. Aber das wäre erst einmal zweitrangig.
